language: go
sudo: required
services:
  - docker
go:
  - 1.10.3
script:
  - go build -ldflags "-s -w -X main.build=$TRAVIS_BUILD_NUMBER" -a -tags netgo
  - docker build -t chatkitinc/drone-docker-tagger .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push chatkitinc/drone-docker-tagger;
    docker tag chatkitinc/drone-docker-tagger chatkitinc/drone-docker-tagger:0.1.$TRAVIS_BUILD_NUMBER;
    docker push chatkitinc/drone-docker-tagger:0.1.$TRAVIS_BUILD_NUMBER;
    fi
